<?php

require_once '../includes/config.php';
require '../vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

$options = new Options();

$options->set('isRemoteEnabled', true);

$dompdf = new Dompdf($options);

$pdo = getDB();
$logoPath =
__DIR__.'/../comp-logo/logo.png';

$type =
pathinfo(
    $logoPath,
    PATHINFO_EXTENSION
);

$data =
file_get_contents(
    $logoPath
);

$logo =
'data:image/'.
$type.
';base64,'.
base64_encode(
    $data
);

$filter = $_GET['filter'] ?? 'today';
if($filter=='today'){

    $stmt = $pdo->query("

        SELECT

        e.full_name,

        a.check_in,

        a.check_out,

        a.total_hours

        FROM employee_attendance a

        JOIN employees e

        ON a.employee_id=e.id

        WHERE DATE(a.check_in)=CURDATE()

        ORDER BY a.check_in DESC

    ");

}

elseif($filter=='week'){

    $stmt = $pdo->query("

        SELECT

        e.full_name,

        a.check_in,

        a.check_out,

        a.total_hours

        FROM employee_attendance a

        JOIN employees e

        ON a.employee_id=e.id

        WHERE YEARWEEK(a.check_in)=YEARWEEK(NOW())

        ORDER BY a.check_in DESC

    ");

}

else{

    $stmt = $pdo->query("

        SELECT

        e.full_name,

        a.check_in,

        a.check_out,

        a.total_hours

        FROM employee_attendance a

        JOIN employees e

        ON a.employee_id=e.id

        WHERE MONTH(a.check_in)=MONTH(NOW())

        AND YEAR(a.check_in)=YEAR(NOW())

        ORDER BY a.check_in DESC

    ");

}

$rows = $stmt->fetchAll();
$total=count($rows);

$present=0;

foreach($rows as $row){

if(!$row['check_out']){

$present++;

}

}

$completed=
$total-$present;
$html='

<style>

body{
font-family:Arial,sans-serif;
font-size:12px;
color:#222;
}

.header{
text-align:center;
margin-bottom:20px;
}

.header img{
height:80px;
}

.title{
font-size:28px;
font-weight:bold;
color:#1e293b;
}

.subtitle{
font-size:16px;
color:#64748b;
}

table{
width:100%;
border-collapse:collapse;
margin-top:20px;
}

th{
background:#1e293b;
color:white;
padding:10px;
}

td{
padding:8px;
border:1px solid #ddd;
}

tr:nth-child(even){
background:#f8fafc;
}

.footer{
margin-top:40px;
text-align:center;
font-size:11px;
color:#666;
}
</style>'
;

$html .= '

<div class="header">

<img src="'.$logo.'">

<div class="title">

AMBITIOUS GROUP

</div>

<div class="subtitle">

Employee Attendance Report

</div>

</div>

<hr>

';
$html .= '

<b>Filter:</b>

'.ucfirst($filter).'

<br><br>

<b>Generated:</b>

'.date('d M Y h:i A').'

<hr>

';
$html .= '

<table>

<tr>
<th>Total Employees</th>
<th>Present</th>
<th>Completed</th>

</tr>

<tr>

<td>'.$total.'</td>

<td>'.$present.'</td>

<td>'.$completed.'</td>

</tr>

</table>

<br><br>

';
$html .= '

<table>

<tr>

<th>Employee</th>

<th>Check In</th>

<th>Check Out</th>

<th>Total Hours</th>

</tr>

';
foreach($rows as $row){

$html .= '

<tr>

<td>'.$row['full_name'].'</td>

<td>'.date(
'h:i A',
strtotime($row['check_in'])
).'</td>

<td>'.

(
$row['check_out']

?

date(
'h:i A',
strtotime($row['check_out'])
)

:

'-'

)

.'</td>

<td>'.

(
$row['total_hours']

?

$row['total_hours']

:

'-'

)

.'</td>

</tr>

';

}
$html .= '

</table>

<br><br><br>

<div style="margin-top:50px">

<table style="width:100%;border:none">

<tr>

<td style="border:none;text-align:left">

Prepared By

<br><br><br>

_________________

</td>

<td style="border:none;text-align:right">

HR Manager

<br><br><br>

_________________

</td>

</tr>

</table>

</div>

<div class="footer">

Generated by Ambitious Group Visitor & Employee Management System

<br>

Dubai, UAE

</div>

';
$dompdf->loadHtml($html);

$dompdf->setPaper('A4','landscape');

$dompdf->render();

$dompdf->stream(
    'attendance_report.pdf',
    [
        'Attachment'=>true
    ]
);